// ─── 100 Compliments ─────────────────────────────────────
const compliments = [
  // Original & refined
  "You have the kindest soul nobody truly deserves.",
  "Your smile can light up every darkness that exists.",
  "You are pure sunshine on a cloudy day.",
  "You're the kind of person people write poetry about.",
  "You make ordinary moments feel extraordinary.",
  "You bring warmth wherever you go.",
  "You are effortlessly graceful.",
  "You have the most calming presence.",
  "Your modesty makes you glow the most.",
  "The way you care is truly rare.",
  "You make 'being kind' look easy.",
  "You're more lovely than the word 'lovely' itself.",
  "You handle everything with such grace and softness.",
  "You inspire calm in the middle of chaos.",
  "You have a voice that soothes storms.",
  "You listen like you truly hear people.",
  "You are the definition of soft strength.",
  "You are elegance in human form.",
  "Your sincerity is like poetry.",
  "You make silence feel beautiful.",
  "You make the world a little softer just by existing.",
  "You are the first page of everyone's favourite book.",
  "You radiate a kindness that makes people believe again.",
  "You are what healing would look like if it had a face.",
  "You're the reason some people still believe in good.",
  "You are the gentle reminder the world needs.",
  "You carry a grace not taught, but born from love.",
  "Your voice is the kind that echoes in people's minds long after.",
  "You're a safe place in a very noisy world.",
  "You are moonlight wrapped in human form.",
  "You're not just kind — you're kindness itself.",
  "No star can outshine the spark of your eyes.",
  "You are the sun — a necessity, not a luxury.",
  "You shine in ways words can't quite hold.",
  "You wear humility, peace, and kindness like a crown.",
  "You are a masterpiece no artist could ever capture.",
  "Your voice is sweeter than all the sweetness in the world combined.",
  "Your silence is more special than the quiet of early morning.",
  "You see the good when others forget to look.",
  "Everything you touch turns golden.",
  "You are the very definition of a wonderful human being.",
  "You are the rare kind of beautiful that only deepens with time.",
  "You are deeper than all the ocean's depth.",
  "No algorithm could ever understand you — you're beyond calculation.",
  "No one can match the beauty you carry inside and out.",
  // New compliments
  "You have a way of making people feel seen without even trying.",
  "You are the calm everyone searches for but rarely finds.",
  "Your presence alone is a form of kindness.",
  "You carry warmth in your words that lingers for days.",
  "You are the kind of rare that makes people grateful to know you.",
  "There is something eternal in the way you love.",
  "You are someone the universe took extra time to create.",
  "Your gentleness is not weakness — it is the rarest strength.",
  "You are someone whose memory makes people smile.",
  "Even your smallest gestures carry the weight of real love.",
  "You make people feel like they matter — and that is everything.",
  "The world is measurably better because you are in it.",
  "You are the answer to questions people didn't know they had.",
  "You hold more light than you will ever see in a mirror.",
  "You are not just good — you are the kind of good that restores faith.",
  "Your laugh is the sound the world needs more of.",
  "You have a soul the depth of which cannot be measured.",
  "You are everything soft and strong at once.",
  "Your care for others is one of the finest things about you.",
  "You exist in a league of your own — quietly, beautifully.",
  "The way you carry yourself tells a story of dignity and grace.",
  "You are someone people describe as 'the good one' in every room.",
  "You are made of the kind of stuff that stories remember.",
  "You are the friend everyone hopes to one day find.",
  "You love deeply, and that is your most beautiful quality.",
  "Your honesty is a gift so rare most people don't recognise it.",
  "You have the kind of beauty that time only improves.",
  "You are proof that being gentle is the bravest thing.",
  "You are the kind of soul that leaves rooms feeling lighter.",
  "You have a heart that gives without keeping score.",
  "You are more than enough — in every possible way.",
  "Your loyalty is something people carry like treasure.",
  "You speak with care in a world that forgets to.",
  "You are a living reminder that kindness is power.",
  "You have the ability to make ordinary days feel like gifts.",
  "You are someone worth knowing deeply.",
  "Your thoughtfulness is extraordinary in the most ordinary moments.",
  "You bring a kind of peace that money cannot buy and time cannot teach.",
  "You are genuinely one of the good ones.",
  "There is magic in the way you notice things others miss.",
  "Your soul must have been made on a very good day.",
  "You are the reason certain people believe they deserve kindness.",
  "You are quietly one of the most remarkable people alive.",
  "The stars themselves are a little envious of your glow.",
  "You are what tenderness would look like if it took human form.",
  "You are the morning feeling — soft, hopeful, and golden.",
  "You are the kind of beautiful that has nothing to do with mirrors.",
  "Your kindness has changed more lives than you will ever know.",
  "You are someone whose existence is genuinely a blessing.",
  "You are a whole universe in one person — boundless and breathtaking.",
  "You are the reminder that something truly lovely still exists in this world.",
  "You are living proof that grace is a real thing.",
  "Even the way you disagree is kind.",
  "You have a gift for making people feel at home.",
  "You are rare in all the best ways.",
];

function showCompliment() {
  const index = Math.floor(Math.random() * compliments.length);
  document.getElementById('compliment').textContent = compliments[index];
}

